### ISSUE TITLE
Simplified Chinese Language Pack

### ISSUE THREAD

**Issue by shenyx110** [NinjaBunny1/More-Enchantments#12]
Simplified Chinese Language Pack

**Comment by shenyx110** [comment]
[MoreEnchantments.zip](https://github.com/NinjaBunny1/More-Enchantments/files/12484603/MoreEnchantments.zip)

**Comment by NinjaBunny1** [comment]
Thank you for your interest in my mod! Unfortunately, I had to discontinue support for other languages due to technical problems. I will contact you, when I recontinue support.
