### ISSUE TITLE
Reparation

### ISSUE THREAD

**Issue by Enrico9431** [NinjaBunny1/More-Enchantments#4]
How exactly does it work, like how often and how much does it repair and also does it work outside a player's inventory?

**Comment by NinjaBunny1** [comment]
On any player tick (20 times a second) there is a procedure being called. This procedure has a 1% Chance of repairing all items with the entchantemnt in both hands and all armor slots by one. It doesn't work with items in any other slot may it be in the players inventory or in that of an entity or block. Ideally it would, but I decided against that for sake of simplicity and performance.
