### ISSUE TITLE
Empty Tags NBT data appended when item is held

### ISSUE THREAD

**Issue by NoveritaDev** [NinjaBunny1/More-Enchantments#7]
When a player holds an item with this mod, it adds an empty "Tags:{}" section to the NBT data for that itemstack. This results in it being unable to stack with other items. It applies this tag regardless of if anything is done with the item, it just needs to be held.

I can supply a mod  list if you believe this is the result of interaction with another mod.

**Comment by vladamaca** [comment]
Hello,
I have the same issue. When I create new world, then dig dirt, that dirt I pick up have changed data - this mod adding "tag: {}". It prevents items from stacking and you need to move new picked up item into hand to also add "tag" and to be able to stack them.
![image](https://user-images.githubusercontent.com/47114208/201875694-562d930a-e494-4040-8826-630f5032b484.png)

**Comment by JacksonRoyal** [comment]
I have the same problem, my chests and inventory are full of split and non-stackable items. Has the author already commented on this?

**Comment by RealMagicGamer** [comment]
Also happens to me yeah. The only way to stack them again is by dropping those blocks and picking them up again.

**Comment by Wubzzz1337** [comment]
No news on this damn :o

**Comment by Pvtatomxne** [comment]
is there any way to maybe create a command block that repeats a command that removes every nbt tag? i have the same problem and id really like to keep using the mod

**Comment by NinjaBunny1** [comment]
Sorry for my late answer, but I took a long break form programming. I will fix this bug with version 1.4.3. The patch notes are as follows:
Indestructibility doesn't try to effect unstackable items anymore and therefore stopped to interfere with the stackability of items. This does NOT apply in retrospect. All items already unstackable will stay unstackable.

**Comment by Pvtatomxne** [comment]
thank you so much man, love this mod and would rather like to not *not* use it
